# Generated by Django 3.2.3 on 2022-06-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='certificate_type',
            field=models.CharField(choices=[('CA_G', 'Campus Ambassador Gold'), ('CA_P', 'Campus Ambassador Platinum'), ('CA_S', 'Campus Ambassador Silver'), ('CA_Part', 'Campus Ambassador Participation'), ('P', 'Participant'), ('W', 'Winner'), ('SA', 'Special Achievement'), ('MP', 'Manshakti Participant'), ('MW', 'Manshakti Winner')], default='CA', max_length=30),
        ),
    ]
