# Generated by Django 4.0.5 on 2022-09-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_candidate_certificate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='certificate_type',
            field=models.CharField(choices=[('CA_G', 'Campus Ambassador Gold'), ('CA_P', 'Campus Ambassador Platinum'), ('CA_S', 'Campus Ambassador Silver'), ('CA_Part', 'Campus Ambassador Participation'), ('P', 'Participant'), ('W', 'Winner'), ('R1', 'First Runner'), ('R2', 'Second Runner'), ('R', 'Runner'), ('SA', 'Special Achievement'), ('MP', 'Manshakti Participant'), ('MW', 'Manshakti Winner')], default='CA', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='event',
            field=models.CharField(choices=[('None', 'None'), ('Haute Couture', 'Haute Couture'), ('States of Dress', 'States of Dress'), ('Glamour Nova', 'Glamour Nova'), ('Rock-O-Phonix', 'Rock-O-Phonix'), ('Mr & Miss Alcheringa', 'Mr & Miss Alcheringa'), ('Crossfade', 'Crossfade'), ('Alcher Got Talent', 'Alcher Got Talent'), ('Rap Battle', 'Rap Battle'), ('Theatrix', 'Theatrix'), ('Monodrama', 'Monodrama'), ('Halla Bol', 'Halla Bol'), ('Electric Heels', 'Electric Heels'), ('Step Up', 'Step Up'), ('Short Cut', 'Short Cut'), ('Sixth String', 'Sixth String'), ('Navras', 'Navras'), ('Raga High', 'Raga High'), ('Unplugged', 'Unplugged'), ('Voice of Alcheringa', 'Voice of Alcheringa'), ('Choir', 'Choir'), ('Just A Minute', 'Just A Minute'), ('Mehfil - e - Alcheringa', 'Mehfil - e - Alcheringa'), ('Parliamentry Debate', 'Parliamentry Debate'), ('Poetry Slam - Hindi', 'Poetry Slam - Hindi'), ('Poetry Slam - English', 'Poetry Slam - English'), ('Zephyr', 'Zephyr'), ('Face Art', 'Face Art'), ('Ink The Tee', 'Ink The Tee'), ('Graffiti', 'Graffiti'), ('Clay Modelling', 'Clay Modelling'), ('Live Sketching', 'Live Sketching'), ('Rangoli', 'Rangoli'), ('Who is it?', 'Who is it?'), ('5 on 5 football', '5 on 5 football'), ('Arm Wrestling', 'Arm Wrestling'), ('3 on 3 Basketball', '3 on 3 Basketball'), ('Gully Cricket', 'Gully Cricket'), ('3 on 3 Volleyball', '3 on 3 Volleyball'), ("Director's Cut", "Director's Cut"), ('Musically', 'Musically'), ('Snap Thrillz', 'Snap Thrillz'), ('Custom Brush', 'Custom Brush'), ('Doodle Pad', 'Doodle Pad'), ('Alcher Diva/Hunk', 'Alcher Diva/Hunk'), ('Xpressions', 'Xpressions'), ('Parliamentry Debate', 'Parliamentry Debate'), ('General Quiz', 'General Quiz'), ('Business Quiz', 'Business Quiz'), ('Sports Quiz', 'Sports Quiz'), ('Entertainment Quiz', 'Entertainment Quiz'), ('Comic Quiz', 'Comic Quiz'), ('India Quiz', 'India Quiz'), ('Manshakti Poetry', 'Manshakti Poetry'), ('Manshakti Art', 'Manshakti Art'), ('Critical Damage', 'Critical Damage'), ('Just Reel It', 'Just Reel It'), ('Best out of Waste', 'Best out of Waste'), ('Sixth String', 'Sixth String')], default='', max_length=50),
        ),
    ]
